[package]
name = "solana-yellowstone-blocklist"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program = "2.0.9"
borsh = "1.5.1"
thiserror = "1.0.63"
bincode = "1.3.3"
serde_derive = "1.0.145" 
serde = { version = "1.0.145" }
bytemuck = "1.19.0"
getrandom = { version = "0.1.14", features = ["dummy"] }
# getrandom = { version = "0.1.14", features = ["dummy"] }

[dev-dependencies]
assert_matches = "1.5.0"
solana-logger = "=2.0.9"
solana-program-test = "=2.0.9"
# solana-test-validator = "=2.0.2"
solana-sdk = "=2.0.9"
borsh = "1.5.1"

[lib]
crate-type = ["cdylib", "lib"]
doctest = false