[workspace]
resolver = "2"
members = ["yellowstone-blocklist", "yellowstone-blocklist-cli"]

[workspace.dependencies]
solana-program = "~2.0.14"
borsh = "1.5.1"
thiserror = "1.0.58"
bincode = "1.3.3"
serde_derive = "1.0.145"
serde = { version = "1.0.145" }
bytemuck = "1.19.0"
getrandom = { version = "0.1.14", features = ["dummy"] }

[workspace.metadata.patch.crates-io]
solana-program = { git = "https://github.com/rpcpool/solana-public.git", tag = "v2.0.14-triton-public" }
solana-sdk = { git = "https://github.com/rpcpool/solana-public.git", tag = "v2.0.14-triton-public" }
