[package]
name = "solana-yellowstone-blocklist"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []

[dependencies]
solana-program = "2.0.9"
borsh = "1.5.1"
thiserror = "1.0.63"
serde = { version = "1.0.145" }
getrandom = { version = "0.1.14", features = ["dummy"] }
# getrandom = { version = "0.1.14", features = ["dummy"] }


[dev-dependencies]
solana-config-program = "2.0.9"

[lib]
crate-type = ["cdylib", "lib"]
