[workspace]
resolver = "2"
members = ["yellowstone-blocklist", "yellowstone-blocklist-cli"]

[workspace.dependencies]
pinocchio = "0.7.1"
pinocchio-pubkey = "0.2.2"
pinocchio-system = "0.2.1"
borsh = "1.5.5"
borsh-derive = "1.5.5"
thiserror = "1.0.58"
bincode = "1.3.3"
serde_derive = "1.0.145"
serde = { version = "1.0.145" }
bytemuck = "1.19.0"
getrandom = { version = "0.1.14", features = ["dummy"] }
