[workspace]
resolver = "2"
members = [
  "yellowstone-blocklist",
  "yellowstone-blocklist-cli",
  "yellowstone-blocklist-rust-sdk",
]

[workspace.dependencies]
solana-program = "~2.1.11"
borsh = "1.5.1"
thiserror = "2.0.12"
bincode = "1.3.3"
serde_derive = "1.0.145"
serde = { version = "1.0.145" }
bytemuck = "1.19.0"
getrandom = { version = "0.1.14", features = ["dummy"] }
solana-client = "~2.1.11"
solana-sdk = "~2.1.11"
solana-yellowstone-blocklist = { path = "yellowstone-blocklist" }
solana-yellowstone-blocklist-rust-sdk = { path = "yellowstone-blocklist-rust-sdk" }

[workspace.metadata.patch.crates-io]
solana-program = { git = "https://github.com/rpcpool/solana-public.git", tag = "v2.1.11-triton-public" }
solana-sdk = { git = "https://github.com/rpcpool/solana-public.git", tag = "v2.1.11-triton-public" }
